on:
  pull_request:
    branches:
      - *
    types: [closed]

jobs:
  update-expected-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: check out to merged branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.ref}}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - name: update expect screenshot
        env:
          BOT_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit --allow-empty -m "update expected screenshot"
          git push "https://${{env.BOT_TOKEN}}@github.com/${{github.repository}}.git"
