name: pattern-a-if(A->B/B->C)
on: 
    pull_request: 
        branches: 
            - '**'
jobs:
    job1:
        runs-on: 
            ubuntu-latest
        steps:
            - run: echo job1
            - run: if [ contains(github.event.issue.labels.*.name, 'failjob1') -eq "true" ]; then
                        exit 1
                    else 
                        echo success job1
                    fi
    job2:
        needs: job1
        runs-on: 
            ubuntu-latest
        steps:
            - run: echo job2
            - run: if [ contains(github.event.issue.labels.*.name, 'failjob2') -eq "true" ]; then
                        exit 1
                    else 
                        echo success job2
                    fi
    job3: 
        needs: job2
        runs-on: 
            ubuntu-latest
        steps:
            - run: echo job3
            - run: echo success job3
