name: GitHub Actions Demo
on:
  issue_comment:
    types: [edited]

jobs:
    # This job only runs for pull request comments
    notify-edited:
      name: PR comment
      if: ${{ github.event.issue.pull_request }}
      runs-on: ubuntu-latest
      steps:
          - run: echo detected-editing
