name: PR Commented
on:
  issue_comment:
    types: [created, edited]
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
          echo change
          echo $CHANGES
          echo $FROM
        env:
          NUMBER: ${{ github.event.issue.number }}
          CHANGES: ${{ github.event.issue.changes }}
          FROM: ${{ github.event.issue.changes[body][from] }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}