name: PR Commented
on:
  issue_comment:
    types: [created, edited]
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJson(github.event.changes) }}' | jq ".body.from" | xargs echo "previous value:" >> message
          echo '${{ toJson(github.event.comment) }}' | jq ".body" | xargs echo "current value:" >> message
          cat message
          
          echo '${{ toJson(github.event.changes) }}' | 
          jq ".body.from" |
          grep -oE "\- \[ \]|\- \[x\]" |
          wc -l |
          xargs -IVAL echo "previous_task_count=VAL" >> $GITHUB_ENV
          
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".body" |
          grep -oE "\- \[ \]|\- \[x\]" |
          wc -l |
          xargs -IVAL echo "current_task_count=VAL" >> $GITHUB_ENV
          
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".body" |
          grep -oE "\- \[x\]" |
          wc -l |
          xargs -IVAL echo "finished_task_count=VAL" >> $GITHUB_ENV
          
          echo '${{ toJson(github.event.changes) }}' | 
          jq ".body.from" |
          grep -oE "\- \[ \]" |
          wc -l |
          xargs -IVAL echo "unfinished_task_count=VAL" >> $GITHUB_ENV
      - if: ${{ env.finished_task_count != 1 || env.unfinished_task_count != 1 || env.previous_task_count != 1 || env.current_task_count != 1 }}
        run: exit 1
  update-expected-image:
    name: do update expected image
    needs: pr_commented
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.head_ref }}
      # GitHub CLI api
      # https://cli.github.com/manual/gh_api
      - name: gh api
        run: gh api /repos/ShebangDog/ci_sandbox/issues/6/comments
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
          

