name: PR Commented
on:
  issue_comment:
    types: [created, edited]
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJson(github.event.changes) }}' | jq ".body.from" | xargs echo "previous value: " >> message
          echo '${{ toJson(github.event.comment) }}' | jq ".body" | xargs echo "current value: " >> message
          
          echo '${{ toJson(github.event.changes) }}' | 
          jq ".body.from" |
          grep -oE "\- \[ \]|\- \[x\]" |
          wc -l |
          xargs echo |
          xargs printf "%s%s\n" "previous_task_count=" |
          xargs echo >> $GITHUB_ENV
          
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".body" |
          grep -oE "\- \[ \]|\- \[x\]" |
          wc -l |
          xargs echo |
          xargs printf "%s%s\n" "current_task_count=" |
          xargs echo >> $GITHUB_ENV
          
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".body" |
          grep -oE "\- \[x\]" |
          wc -l |
          xargs echo |
          xargs printf "%s%s\n" "finished_task_count=" |
          xargs echo >> $GITHUB_ENV
          
          echo '${{ toJson(github.event.changes) }}' | 
          jq ".body.from" |
          grep -oE "\- \[ \]" |
          wc -l |
          xargs echo |
          xargs printf "%s%s\n" "unfinished_task_count=" |
          xargs echo >> $GITHUB_ENV

        env:
          NUMBER: ${{ github.event.issue.number }}
          COMMENT: ${{ toJson(github.event.comment) }}
          CHANGES: ${{ toJson(github.event.changes) }}
      - run: |
          echo "task is complete"
        if: ${{ env.finished_task_count == 1 && env.unfinished_task_count == 1 && env.previous_task_count == 1 && env.current_task_count == 1 }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}