name: PR Commented
on:
  issue_comment:
    types: [created, edited]
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
          echo change
          echo $COMMENT
          echo $CHANGES
          echo '${{ toJson(github.event.changes) }}' | jq ".body.from"
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".body" |
          grep -o "\- \[ \]" |
          wc -l |
          xargs echo |
          xargs printf "%s%s\n" "checkbox_count=" >> $GITHUB_ENV
        env:
          NUMBER: ${{ github.event.issue.number }}
          COMMENT: ${{ toJson(github.event.comment) }}
          CHANGES: ${{ toJson(github.event.changes) }}
      - run: |
          echo "have no task"
        if: ${{ env.checkbox_count == 0 }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}