on: 
    pull_request
jobs:
    echo-diff-with-command:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: check-current-directory
              run: ls
            - name: fetch-base-branch
              run: git fetch origin ${{github.base_ref}}:${{github.base_ref}}
            - name: setting-diff_files
              run: |
                git diff --name-only HEAD ${{github.base_ref}} -- "./src" >> diff.txt
                echo "debug"
                cat diff.txt
            - name: use-diff_files
              run: |
                cat diff.txt
                cat diff.txt | echo
                