name: status-code-if
on: 
    pull_request
jobs:
    job1:
        runs-on: 
            ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'dojob1')
        steps:
            - run: |
                if [ "${{ contains(github.event.pull_request.labels.*.name, 'failjob1') }}" = "true" ]; then
                    exit 1
                else
                    exit 0
    job2:
        runs-on: 
            ubuntu-latest
        if: always()
        needs: job1
        steps: 
            - run: echo ${{ job.status }}
    job3:
        runs-on:
            ubuntu-latest
        if: cancelled()
        needs: job1
        steps: 
            - run: echo ${{ job.status }}
    job4:
        runs-on:
            ubuntu-latest
        if: success()
        needs: job1
        steps: 
            - run: echo ${{ job.status }}
    job5:
        runs-on:
            ubuntu-latest
        if: failure()
        needs: job1
        steps: 
            - run: echo ${{ job.status }}
